services:
    app.form.type.task:
        class: AppBundle\Form\Type\FormType
        tags: 
            - { name: form.type }

    app.form.type.task1:
        class: AppBundle\Form\Type\RegisterType
        tags: 
            - { name: form.type }
            
    app.token_authenticator:
        class: AppBundle\Security\TokenAuthenticator
        arguments: ['@doctrine.orm.entity_manager']